name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          files: Database Localization
          args: "--no-color -q"

      - name: setup python
        uses: actions/setup-python@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          python-version: 3.8

      - name: run python scripts
        if: ${{ github.event_name != 'pull_request' }}
        run: python changelog.py && python build.py

      - name: Send Status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
        if: ${{ failure() }}

#      - name: Create Package
#        uses: BigWigsMods/packager@master
#        if: ${{ github.event_name != 'pull_request' }}
#        with:
#          args: -g classic
#        env:
#          CF_API_KEY: ${{ secrets.CF_API_KEY }}
#          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
#          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
#          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
